# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_initial',
                'doc_host': 'https://ImtiazKhanDS.github.io',
                'git_url': 'https://github.com/ImtiazKhanDS/nbdev_initial',
                'lib_path': 'nbdev_initial'},
  'syms': {'nbdev_initial.core': {'nbdev_initial.core.foo': ('core.html#foo', 'nbdev_initial/core.py')}}}
